---
- hosts: dev-01
  become: yes
  become_user: root
  vars:
    # githubuser: ""
    # githubtoken: ""
    dest: "/var/www/site/"
    ansistrano_deploy_via: "git"
    ansistrano_git_repo: "git@github.com:crazy4devops/simplephpapp.git"
    ansistrano_deploy_to: "{{ dest }}"
    ansistrano_keep_releases: 3
    ansistrano_git_identity_key_path: "ssh-priv-keys/id_rsa_dev01"
    # ansistrano_shared_paths:
    #   - "img"
    #   - "css"
    # ansistrano_shared_files:
    #   - "log"
    # ansistrano_git_repo_tree: 'html'
    # ansistrano_git_branch: 'releases/v1.1.0'

  roles:
     - { role: ansistrano.deploy }
