---
- hosts: dev-01
  become: yes
  become_user: root
  vars:
    dest: "/var/www/site/"
    apache_global_vhost_settings: |
      DirectoryIndex index.php index.htm
    apache_vhosts:
      - servername: "website"
        documentroot: "{{ dest }}current/html"

  tasks:

    - name: create directory for website
      file:
        path: /var/www/site/
        state: directory
        mode: 0755

    - name: install git
      package:
        name: git
        state: latest

    # - name: permit traffic in default zone for http service
    #   ansible.posix.firewalld:
    #     service: http
    #     permanent: yes
    #     state: enabled
    #     immediate: yes

  roles:
    - { role: geerlingguy.apache }
